config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :bookings, only: %i[index edit update destroy]
  end

  resources :users, only: %i[show]
  resources :bookings, only: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  include PricingEngine

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :animal_name, presence: true
  validates :animal_type, presence: true

  validate :valid_hours_requested
  validate :date_of_service_check

  private

  def valid_hours_requested
    errors.add(:hours_requested, 'must be between 2 and 8') unless hours_requested&.between?(2, 8)
  end

  def date_of_service_check
    return unless (date_of_service || Date.today) <= Date.today

    errors.add(:date_of_service, "must be greater than #{Date.today}")
  end
end

app/models/concerns/pricing_engine.rb
module PricingEngine
  BASE_CHARGE = 20
  PRICING = {
    'Dog' => 10,
    'Cat' => 5
  }.freeze

  def subtotal
    additional_charge = (hours_requested - 1) * PRICING[animal_type]
    BASE_CHARGE + additional_charge
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  belongs_to :sitter, class_name: 'PetSitter', optional: true

  validates :pet_name, presence: true
  validates :species, presence: true

  enum species: %w[Cat Dog]
end

app/models/pet_sitter.rb
class PetSitter < ApplicationRecord
  validates :sitter_name, presence: true
  validates :contact_info, presence: true

  has_many :pets, foreign_key: :sitter_id, inverse_of: :sitter
  has_many :owners, through: :pets, source: :owner
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pets, foreign_key: 'owner_id', inverse_of: :owner

  has_many :pet_sitters, through: :pets, source: :owner

  validates :username, presence: true
  validates :email, presence: true
end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])

    if @booking.update(booking_params)
      flash[:notice] = 'Booking was successfully updated.'
      redirect_to admin_bookings_path
    else
      flash[:alert] = @booking.errors.full_messages.join(', ')
      redirect_to edit_admin_booking_path(@booking)
    end
  end

  def destroy
    Booking.find(params[:id]).destroy

    flash[:notice] = 'Booking was successfully deleted.'
    redirect_to admin_bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(
      :first_name,
      :last_name,
      :animal_name,
      :animal_type,
      :hours_requested,
      :date_of_service
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    booking = Booking.new(booking_params)

    if booking.save
      flash[:notice] = 'Booking was successfully created.'
      redirect_to bookings_path
    else
      flash[:alert] = booking.errors.full_messages.join(', ')
      redirect_to new_booking_path
    end
  end

  private

  def booking_params
    params.require(:booking).permit(
      :first_name,
      :last_name,
      :animal_name,
      :animal_type,
      :hours_requested,
      :date_of_service
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @pets = @user.pets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/bookings/edit.html.erb
<h1>Update Booking</h1>

<%= form_with(model: Booking, url: admin_booking_path, method: :patch) do |form| %>
    <%= render "shared/form_fields", form: form, booking: @booking%>
<%= form.submit 'Update' %>
<% end %>

<%= button_to "Delete booking", admin_booking_path(@booking), method: :delete%>

app/views/admin/bookings/index.html.erb
<h1>All Bookings</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Animal Name</th>
      <th>Animal Type</th>
      <th>Hours Requested</th>
      <th>Date of Service</th>
      <th>Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr id='id-<%= booking.id %>'>
        <td><%= booking.first_name %></td>
        <td><%= booking.last_name %></td>
        <td><%= booking.animal_name %></td>
        <td><%= booking.animal_type %></td>
        <td><%= booking.hours_requested %></td>
        <td><%= booking.date_of_service %></td>
        <td><%= booking.subtotal %></td>
        <td><%= link_to "Update this booking", edit_admin_booking_path(booking)%></td>
      </tr>
    <% end %>
</table>

app/views/bookings/index.html.erb
<h1>All Bookings</h1>
<h2> <%= link_to 'Book another Pet', new_booking_path %> </h2>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Animal Name</th>
      <th>Animal Type</th>
      <th>Hours Requested</th>
      <th>Date of Service</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr id="id-<%= booking.id %>" >
        <td><%= booking.first_name %></td>
        <td><%= booking.last_name %></td>
        <td><%= booking.animal_name %></td>
        <td><%= booking.animal_type %></td>
        <td><%= booking.hours_requested %></td>
        <td><%= booking.date_of_service %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<h1>Book a Cat or Dog Sitting</h1>
<%= form_with(model: Booking, url: bookings_path, method: :post) do |form| %>
    <%= render "shared/form_fields", form: form, booking: @booking%>
<%= form.submit 'Book' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsSitting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/shared/_form_fields.html.erb
<p>
    <%= form.label :first_name %>
    <%= form.text_field :first_name, value: booking&.first_name %>
</p>

<p>
    <%= form.label :last_name %>
    <%= form.text_field :last_name, value: booking&.last_name %>
</p>

<p>
    <%= form.label :animal_name %>
    <%= form.text_field :animal_name, value: booking&.animal_name %>
</p>

<p>
    <%= form.label :animal_type %>
    <%= form.select :animal_type, ['Dog', 'Cat'] %>
</p>

<p>
    <%= form.label :hours_requested %>
    <%= form.number_field :hours_requested, in: 2..8, value: booking&.hours_requested %>
</p>

<p>
    <%= form.label :date_of_service %>
    <%= form.date_field :date_of_service, min: Date.today, value: booking&.date_of_service %>
</p>

app/views/users/show.html.erb
<h2> Username: <%= @user.username %> </h2>

<h2> Pets: </h2>
<% @pets.each do |pet| %>
  <p>Pet Name: <%= pet.pet_name %> </p>
  <p>Species: <%= pet.species %> </p>
  <p>Age: <%= pet.age %> </p>
  <p>Sitter: <%= pet.sitter.sitter_name %> </p>
<% end %>